//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MISPEMAEntities : DbContext
    {
        public MISPEMAEntities()
            : base("name=MISPEMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADRM_TBL_USER_MASTER> ADRM_TBL_USER_MASTER { get; set; }
        public virtual DbSet<AttendanceDetail> AttendanceDetails { get; set; }
        public virtual DbSet<AttendanceStatu> AttendanceStatus { get; set; }
        public virtual DbSet<TBL_DateofBirths> TBL_DateofBirths { get; set; }
        public virtual DbSet<TBL_MINUTES_OF_MEETING> TBL_MINUTES_OF_MEETING { get; set; }
        public virtual DbSet<TreatmentPlan> TreatmentPlans { get; set; }
        public virtual DbSet<TreatmentPlanDetail> TreatmentPlanDetails { get; set; }
        public virtual DbSet<TreatmentPlanID> TreatmentPlanIDs { get; set; }
        public virtual DbSet<TreatmentRoomMaster> TreatmentRoomMasters { get; set; }
    }
}
